# Generated by Django 4.2.7 on 2024-01-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_name', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('second_name', models.CharField(blank=True, max_length=100)),
                ('team', models.IntegerField(default=0)),
                ('element_type', models.IntegerField(default=0)),
                ('minutes', models.IntegerField(default=0)),
                ('goals_scored', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('clean_sheets', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('photo', models.ImageField(default='default_photo.jpg', upload_to='')),
                ('position', models.CharField(blank=True, max_length=200)),
                ('team_name', models.CharField(blank=True, max_length=200)),
                ('influence', models.DecimalField(decimal_places=3, default=0.0, max_digits=7)),
                ('total_points', models.IntegerField(default=0)),
                ('selected_by_percent', models.CharField(blank=True, max_length=200)),
                ('value_form', models.CharField(blank=True, max_length=200)),
                ('value_season', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
