# Generated by Django 4.2.7 on 2024-01-11 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.player')),
                ('defenders', models.ManyToManyField(blank=True, limit_choices_to={'position': 'Defender'}, related_name='defenders_players', to='app1.player')),
                ('forwards', models.ManyToManyField(blank=True, limit_choices_to={'position': 'Forward'}, related_name='forwards_players', to='app1.player')),
                ('gk', models.OneToOneField(blank=True, limit_choices_to={'position': 'Goalkeeper'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goalkeeper_player', to='app1.player')),
                ('midfielders', models.ManyToManyField(blank=True, limit_choices_to={'position': 'Midfielder'}, related_name='midfielders_players', to='app1.player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
