# Generated by Django 4.2.7 on 2024-01-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_myteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='myteam',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
